dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  http: ^1.2.1
  dio: ^5.5.0+1
  retrofit: ^4.1.0
  json_annotation: ^4.9.0
  
  json_serializable: ^6.8.0

  # 이미지 선택을 위한 패키지 추가
  image_picker: ^1.1.2 # 최신 안정 버전으로 업데이트될 수 있습니다.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  retrofit_generator: ^8.1.1
  build_runner: ^2.4.11